

# This file was *autogenerated* from the file graphMagmaAlgebras.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2)
from sage.matrix.constructor import Matrix
from sage.rings.rational_field import QQ

class bMatrix:
    def __init__(self, dim:tuple, position):
        """
        Initializes a matrix of size (nrows x ncols) with a single entry of 1 at 'position'.
        
        :param nrows: Number of rows
        :param ncols: Number of columns
        :param position: A tuple (i, j) specifying the position of the 1-entry
        """
        nrows=dim[_sage_const_0 ]
        ncols=dim[_sage_const_1 ]
        # Create a zero matrix first
        self.mat = Matrix(QQ, nrows, ncols, _sage_const_0 )
        
        # Ensure position is within bounds
        if len(position)>_sage_const_0 :
            if not (_sage_const_0  <= position[_sage_const_0 ] < nrows and _sage_const_0  <= position[_sage_const_1 ] < ncols):
                raise ValueError("Position is out of bounds.")
            
            # Set the single 1-entry
            self.mat[position] = _sage_const_1 

    def is_valid(self):
        """
        Checks if the matrix has exactly one entry as 1 and all others are 0.
        """
        return sum(self.mat.list()) == _sage_const_1   # Sum of entries should be exactly 1

    def __mul__(self, other):
        """
        Defines the multiplication operation for OneEntryMatrix.
        """
        if isinstance(other, bMatrix):
            return self.mat * other.mat
        else:
            raise TypeError("Unsupported operand type(s) for *: 'OneEntryMatrix' and '{}'".format(type(other).__name__))
    def __add__(self, other):
        """
        Defines the addition operation for OneEntryMatrix.
        """
        if isinstance(other, bMatrix):
            return self.mat + other.mat
        else:
            raise TypeError("Unsupported operand type(s) for +: 'OneEntryMatrix' and '{}'".format(type(other).__name__))
    def __sub__(self, other):
        """
        Defines the subtraction operation for OneEntryMatrix.
        """
        if isinstance(other, bMatrix):
            return self.mat - other.mat
        else:
            raise TypeError("Unsupported operand type(s) for -: 'OneEntryMatrix' and '{}'".format(type(other).__name__))
    def __eq__(self, other):
        """
        Defines the equality operation for OneEntryMatrix.
        """
        if isinstance(other, bMatrix):
            return self.mat == other.mat
        else:
            raise TypeError("Unsupported operand type(s) for ==: 'OneEntryMatrix' and '{}'".format(type(other).__name__))

    def __repr__(self):
        return repr(self.mat)

class graphMagma:
    from sage.matrix.constructor import block_matrix, zero_matrix, identity_matrix, matrix
    from sage.rings.integer_ring import ZZ
    from sage.all import var
    
    #Create a global variable to store the generators
    generators = []
    Inc = matrix(ZZ, _sage_const_0 , _sage_const_0 , [])
    multiplication_table = matrix(SR,_sage_const_0 ,_sage_const_0 ,[])
    #Create a global variable to store the graph
    graph = []
    def __init__(self, graph:list):
        self.graph = graph
        self.generators = self.getGenerators()
        self.Inc = self.getIncidenceMatrix()
        self.multiplication_table = self.getMultiplicationTable()
    def getGenerators(self):
        self.generators = []
        for i in range(len(self.graph)):
            for j in range(self.graph[i][_sage_const_1 ]):
                self.generators.append(var(f"a_{i}_{j}", latex_name=fr"\alpha_{{{i},{j}}}"))
        return self.generators
    def getGraph(self):
        return self.graph
    def incidenceMatrix(self):
        G=self.graph
        I=self.Inc
        for g in G:
            if g[_sage_const_0 ] == 'K':
                I = block_matrix([[I, matrix(I.nrows(), g[_sage_const_1 ],[_sage_const_1 ]*(I.nrows()*g[_sage_const_1 ]))], [zero_matrix(g[_sage_const_1 ], I.ncols()), matrix(g[_sage_const_1 ], g[_sage_const_1 ], [_sage_const_1 ]*(g[_sage_const_1 ]*g[_sage_const_1 ]))]])
            else:
                I = block_matrix([[I, matrix(I.nrows(), g[_sage_const_1 ],[_sage_const_1 ]*(I.nrows()*g[_sage_const_1 ]))], [zero_matrix(g[_sage_const_1 ], I.ncols()), matrix(g[_sage_const_1 ],g[_sage_const_1 ])]])  
        self.Inc = I
    def getIncidenceMatrix(self):
        self.incidenceMatrix()
        return self.Inc  
    def multiplicationTable(self):
        I=self.Inc
        M=matrix(SR,I.nrows(),I.nrows())
        self.getGenerators()
        for i in range(I.nrows()):
            for j in range(I.nrows()):
                if I[i,j]==_sage_const_0 :
                    M[i,j]=self.generators[j]
                else:
                    M[i,j]=self.generators[i]
        self.multiplication_table = M
    def getMultiplicationTable(self):
        self.multiplicationTable()
        return self.multiplication_table

from sage.modules.module import Module
from sage.modules.free_module import VectorSpace
from sage.rings.rational_field import QQ
from sage.matrix.constructor import matrix
from sage.misc.latex import LatexExpr
from sage.misc.table import table
from IPython.display import display, Math


class GraphMagmaModule(Module):
    def __init__(self, algebra, scalar_mults:dict):
        """
        algebra: graphMagmaAlgebra nesnesi
        dimension: Modülün boyutu (vektör uzayı boyutu)
        scalar_mults: graphMagmaAlgebra taban elemanlarının modül taban elemanları üzerindeki etkilerini temsil eden matrisler
        """
        self.algebra = algebra
        self.dimension = next(iter(scalar_mults.values())).nrows()  # Modülün boyutu
        v=SR.var('v',self.dimension)
        self.vector_space = VectorSpace(QQ, self.dimension)  # Vektör uzayı
        
        self.scalar_mults = scalar_mults
        
        # Modülün taban elemanlarını oluştur
        self.basis = [self.vector_space.basis()[i] for i in range(self.dimension)]
    
    def act_on(self, algebra_element:str, vector):
        """
        Modül elemanına algebra elemanı ile çarpım etkisini uygular.
        algebra_element: graphMagmaAlgebra'nın bir elemanı
        vector: Modülün bir elemanı (bir vektör)
        """
        
        # Algebra elemanının vektör uzayı üzerindeki etkisini matris çarpımı olarak uygula
        transformed_vector = self.scalar_mults.get(algebra_element) * vector
        
        return transformed_vector
    
    def __repr__(self):
        return f"GraphMagmaModule over {self.algebra} with dimension {self.dimension}\nBasis: {self.basis}"

    def format_as_string_table(self,data):
        """Formats a list of lists as a rectangular text-based table."""
        col_widths = [max(len(str(row[i])) for row in data) for i in range(len(data[_sage_const_0 ]))]  # Find max width per column

        # Create formatted table as a list of strings
        table_lines = []
        for row in data:
            formatted_row = " | ".join(f"{str(item):<{col_widths[i]}}" for i, item in enumerate(row))  # Left-align
            table_lines.append(formatted_row)
    
        # Join rows with newline
        return "\n".join(table_lines)
    
    def getMultiplicationTable(self,return_table=False):
        """
        Returns the table of the scalar multiplication of the algebra on the module as a string object decorated with vertical and horizontal lines
        after the first row and first column, which consist of algebra basis elements and vector space basis elements, respectively.
        """
        # Create the header row
        dict_basis={self.basis[i]:f"v{i}" for i in range(len(self.basis))}
        header_row = [' |']  + [str(dict_basis[basis_vector]) for basis_vector in self.basis]
        other_rows=[[str(g)+' |']+[str(get_linear_combination(self.act_on(str(g), basis_vector),dict_basis.values())) for basis_vector in self.basis]  for g in self.algebra.gens()]
        all_rows = [header_row] + other_rows
        col_widths = [[len(str(row_item))+_sage_const_2  for row_item in row] for row in other_rows]  
        # Find max width per column
        max_col_widths=[max([w[i] for w in col_widths]) for i in range(len(col_widths[_sage_const_0 ]))]
        max_col_width=max(max_col_widths)
        basis=','.join(dict_basis.values())
        print("Scalar multiplication table on the module with basis " + basis + ":\n")
        strg=''
        # Create header
        strg='%'+str(len(other_rows[_sage_const_0 ][_sage_const_0 ]))+'s'+' '
        for i in range(len(header_row)-_sage_const_1 ):
            strg+='%'+str(max_col_width)+'s'+' '
        print(strg % tuple(header_row))
        strg='%'+str(len(other_rows[_sage_const_0 ][_sage_const_0 ]))+'s'+' '
        # Create horizontal line
        for i in range(len(header_row)-_sage_const_1 ):
            strg+='%'+str(max_col_width)+'s'+' '
        print(strg % tuple(['-'*len(other_rows[_sage_const_0 ][_sage_const_0 ])]+['-'*(max_col_width-_sage_const_2 ) for i in range(len(header_row)-_sage_const_1 )]))
        strg='';count=_sage_const_0 
        for w in col_widths:
            strg='%'+str(len(other_rows[_sage_const_0 ][_sage_const_0 ]))+'s'+' '
            for i in range(len(w)-_sage_const_1 ):
                strg+='%'+str(max_col_width)+'s'+' '
            print(strg % tuple(other_rows[count]))
            strg='';count+=_sage_const_1 
        if return_table:
            return all_rows
    
    def dualize(self):
        dual_scalar_mult={}
        for item in self.scalar_mults.keys():
            dual_scalar_mult[item]=self.scalar_mults[item].transpose()
        return GraphMagmaModule(self.algebra,dual_scalar_mult)

    def submodule(self, generators:list):
        """
        This function returns a submodule of a given module as a GraphMagmaModule
        generators: The generators of the submodule in the ambient module
        """
        actions={}
        W = self.vector_space.span(generators)
        B1=[self.act_on(str(g),v) for v in generators for g in self.algebra.gens()]
        W1=self.vector_space.span(B1)
        while W!=W1:
            W=W1
            B1=[self.act_on(str(g),v) for v in W1.basis() for g in self.algebra.gens()]
            W1=self.vector_space.span(B1)
        B1=[[self.act_on(str(g),v) for v in W1.basis()] for g in self.algebra.gens()]
        CM=Matrix(QQ,W1.basis()).transpose()
        mats=[Matrix(QQ,[CM.solve_right(l) for l in L]).transpose() for L in B1]
        for g in self.algebra.gens():
            actions[str(g)]=mats[self.algebra.gens().index(g)]
        return GraphMagmaModule(self.algebra,actions)
    
    def is_Indecomposable(self,reason=False):
        """
        Check if the module is indecomposable.
        """
        M = symbolic_matrix(self.dimension, self.dimension)
        matrices = [self.scalar_mults[str(g)] for g in self.algebra.gens()]
        eqns = []
        for A in matrices:
            expr1=A*M
            expr2=M*A
            for i in range(self.dimension):
                for j in range(self.dimension):
                    eqns.append(expr1[i,j] == expr2[i,j])

        # Solve the equations
        sol = solve(eqns, M.variables())
        # Check if the solution is idempotent
        eqns1=[]
        sol_mat=Matrix(SR,self.dimension,self.dimension,[s.rhs() for s in sol[_sage_const_0 ]])
        expr3=(sol_mat)**_sage_const_2 
        for i in range(self.dimension):
            for j in range(self.dimension):
                eqns1.append(sol_mat[i,j] == expr3[i,j])
        # Solve the equations
        sol1 = solve(eqns1, sol_mat.variables())
        sol_math_str=latex(sol_mat)
        if reason:
            if len(sol1) > _sage_const_2 :
                print('The module is decomposable since there are more than two idempotent elements of the endomorphism ring of '
                'the form:\n\n')
                display(Math(sol_math_str));print('\n\nfor which ',sol1,'.\n \n')
            elif len(sol1) == _sage_const_2 :
                print('The module is indecomposable since there are two idempotent elements of the endomorphism ring.')
            else:
                print('The module is indecomposable.')
        else:
            return len(sol1) <= _sage_const_2  # If the solutions are only the zero matrix or the identity matrix, the module is indecomposable
    
    def direct_sum(self,other):
        """
        This function returns the direct sum of two modules.
        other: The other module to be summed with the current module
        """
        actions={}
        for g in self.algebra.gens():
            actions[str(g)]=block_diagonal_matrix([self.scalar_mults[str(g)], other.scalar_mults[str(g)]])
        return GraphMagmaModule(self.algebra,actions)
    
    def Endomorphism_Ring(self):
        M = symbolic_matrix(self.dimension, self.dimension)
        matrices = [self.scalar_mults[str(g)] for g in self.algebra.gens()]
        eqns = []
        for A in matrices:
            expr1=A*M
            expr2=M*A
            for i in range(self.dimension):
                for j in range(self.dimension):
                    eqns.append(expr1[i,j] == expr2[i,j])

        # Solve the equations
        sol = solve(eqns, M.variables())
        # Check if the solution is idempotent
        eqns1=[]
        sol_mat=Matrix(SR,self.dimension,self.dimension,[s.rhs() for s in sol[_sage_const_0 ]])
        sol_mat_str=latex(sol_mat)
        print('The endomorphism ring of the module is isomorphic to a subalgebra of the algebra of matrices '
        'of size ',sol_mat.nrows(),'x',sol_mat.ncols(),' consisting of the matrices of the form:\n')
        display(Math(sol_mat_str))
        print('where ',sol_mat.variables(),' is/are element(s) of the', f'{self.vector_space.base_field()}.', '\n \n')
        return sol_mat

def symbolic_matrix(m, n):
        """
        Creates an m x n matrix with symbolic variables as entries.
        
        :param m: Number of rows
        :param n: Number of columns
        :return: Symbolic matrix
        """
        var_list = [f"x{i}{j}" for i in range(m) for j in range(n)]  # Variable names
        variables = SR.var(var_list)  # Declare symbolic variables
        return Matrix(SR, m, n, variables)  # Create symbolic matrix
def get_coefficients(expr):
        """
        Extracts coefficients from a linear combination of basis elements of the graph magma algebra.
        
        :param expr: the linear combination expression
        :return: List of pairs of the form (coefficient , basis elements)
        """
        # Convert the expression to a string and split it into terms
        #expr_str = str(expr).replace(' - ', ' + -')  
        expr_str = str(expr)
        terms = expr_str.split(' + ')
        terms= flatten([term.replace(' - ', '+ -').split('+') for term in terms])  # Handle negative signs
        #replace('-', '+-').split(' + ')

        # Extract coefficients and basis elements
        operators= []
        coefficients = []

        for term in terms:
            if '-' in term:
                basis = term.split('-')
                operators.append('-')
                #basis_elements.append(basis)
            else:
                operators.append('+')
                #basis_elements.append(term)
        for b in terms:
            if '*' in b:
                coeff, basis = b.split('*')
                coefficients.append((coeff, basis))
            else:
                if '-' in b:
                    c = b.replace(' -', '')
                    c=c.replace('-','')
                    coefficients.append((-_sage_const_1 , c))
                else:
                    coefficients.append((_sage_const_1 , b))
        
        #basis_elements=[coeff[1] for coeff in coefficients]
        return coefficients
def get_linear_combination(coordinate_vector,basis):
    strg='+'.join([str(coef)+ '*' +str(b) for coef, b in zip(coordinate_vector, basis) if coef != _sage_const_0  ]) if coordinate_vector else '0'
    res=''
    for item in get_coefficients(strg):
        if item[_sage_const_1 ] != '0':
            if item[_sage_const_0 ]=='1':
                res+='+'+str(item[_sage_const_1 ])
            elif item[_sage_const_0 ]=='-1':
                res+='-'+str(item[_sage_const_1 ])
            else:
                res+=str(item[_sage_const_0 ])+'*'+str(item[_sage_const_1 ])
    if res and res[_sage_const_0 ]=='+':
        res=res[_sage_const_1 :]
    return res if res else '0'
    

